<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Http;
use Livewire\Livewire;
use Tests\TestCase;

class ViewMoviesTest extends TestCase
{
    /** @test */
    public function the_main_page_shows_correct_info()
    {
        Http::fake([
            'https://api.themoviedb.org/3/movie/popular' => Http::response($this->fakePopularMovies()), 200,
            'https://api.themoviedb.org/3/movie/now-playing' => Http::response($this->fakeNowPlayingMovies()), 200,
            'https://api.themoviedb.org/3/genres/movie/list' => Http::response($this->fakeGenres()), 200,
        ]);

        $response = $this->get(route('movies.index'));
        $response->assertSuccessful();
        $response->assertSee('Popular Movies');
        $response->assertSee('Wonder Woman 1984');
        $response->assertSee('Now Playing');
        $response->assertSee('Honest Thief');
        $response->assertSee('Fantasy, Action, Adventure');
    }

    /** @test */
    public function the_movie_page_shows_the_correct_info()
    {
        Http::fake([
            'https://api.themoviedb.org/3/movie/*' => Http::response($this->fakeSingleMovie()), 200,
        ]);

        $response = $this->get(route('movies.show', 529203));
        $response->assertSuccessful();
        $response->assertSee('The Croods: A New Age');
        $response->assertSee('Nicolas Cage');
        $response->assertSee('Mark Mothersbaugh');
        $response->assertSee('Original Music Composer');
    }

    /** @test */
    public function the_search_dropdown_works_correctly()
    {
        Http::fake([
            'https://api.themoviedb.org/3/search/movie?query=jumanji' => Http::response($this->fakeSearchMovies()), 200,
        ]);

        Livewire::test('search-dropdown')
            ->assertDontSee('jumanji')
            ->set('search', 'jumanji')
            ->assertSee('Jumanji: The Next Level');
    }

    private function fakePopularMovies()
    {
        return [
            "page" => 1,
            "results" => [
                0 => [
                    "adult" => false,
                    "backdrop_path" => "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
                    "genre_ids" => [
                        0 => 14,
                        1 => 28,
                        2 => 12,
                    ],
                    "id" => 464052,
                    "original_language" => "en",
                    "original_title" => "Wonder Woman 1984",
                    "overview" => "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
                    "popularity" => 3469.571,
                    "poster_path" => "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
                    "release_date" => "2020-12-16",
                    "title" => "Wonder Woman 1984",
                    "video" => false,
                    "vote_average" => 7.5,
                    "vote_count" => 1274,
                ],
                1 => [
                    "adult" => false,
                    "backdrop_path" => "/z15NpieRw7jL7bKoICwLO5j7FgZ.jpg",
                    "genre_ids" => [
                        0 => 878,
                    ],
                    "id" => 733317,
                    "original_language" => "en",
                    "original_title" => "Monsters of Man",
                    "overview" => "A robotics company vying to win a lucrative military contract team up with a corrupt CIA agent to conduct an illegal live field test. They deploy four weaponized prototype robots into a suspected drug manufacturing camp in the Golden Triangle, assuming they'd be killing drug runners that no one would miss. Six doctors on a humanitarian mission witness the brutal slaughter and become prime targets.",
                    "popularity" => 2453.055,
                    "poster_path" => "/1f3qspv64L5FXrRy0MF8X92ieuw.jpg",
                    "release_date" => "2020-11-19",
                    "title" => "Monsters of Man",
                    "video" => false,
                    "vote_average" => 7.4,
                    "vote_count" => 87,
                ],
                2 => [
                    "adult" => false,
                    "backdrop_path" => "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
                    "genre_ids" => [
                        0 => 12,
                        1 => 14,
                        2 => 10751,
                        3 => 16,
                    ],
                    "id" => 529203,
                    "original_language" => "en",
                    "original_title" => "The Croods: A New Age",
                    "overview" => "After leaving their cave, the Croods encounter their biggest threat since leaving: another family called the Bettermans, who claim and show to be better and evolved. Grug grows suspicious of the Betterman parents, Phil and Hope,  as they secretly plan to break up his daughter Eep with her loving boyfriend Guy to ensure that their daughter Dawn has a loving and smart partner to protect her.  Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
                    "popularity" => 2570.332,
                    "poster_path" => "/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
                    "release_date" => "2020-11-25",
                    "title" => "The Croods: A New Age",
                    "video" => false,
                    "vote_average" => 7.9,
                    "vote_count" => 730,
                ],
            ],
            "total_pages" => 500,
            "total_results" => 10000,
        ];
    }

    private function fakeNowPlayingMovies()
    {
        return [
            "dates" => [
                "maximum" => "2020-12-27",
                "minimum" => "2020-11-09",
            ],
            "page" => 1,
            "results" => [
                0 => [
                    "adult" => false,
                    "backdrop_path" => "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
                    "genre_ids" => [
                        0 => 14,
                        1 => 28,
                        2 => 12,
                    ],
                    "id" => 464052,
                    "original_language" => "en",
                    "original_title" => "Wonder Woman 1984",
                    "overview" => "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
                    "popularity" => 3469.571,
                    "poster_path" => "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
                    "release_date" => "2020-12-16",
                    "title" => "Wonder Woman 1984",
                    "video" => false,
                    "vote_average" => 7.5,
                    "vote_count" => 1274,
                ],
                1 => [
                    "adult" => false,
                    "backdrop_path" => "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
                    "genre_ids" => [
                        0 => 12,
                        1 => 14,
                        2 => 10751,
                        3 => 16,
                    ],
                    "id" => 529203,
                    "original_language" => "en",
                    "original_title" => "The Croods: A New Age",
                    "overview" => "After leaving their cave, the Croods encounter their biggest threat since leaving: another family called the Bettermans, who claim and show to be better and evolved. Grug grows suspicious of the Betterman parents, Phil and Hope,  as they secretly plan to break up his daughter Eep with her loving boyfriend Guy to ensure that their daughter Dawn has a loving and smart partner to protect her.  Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
                    "popularity" => 2570.332,
                    "poster_path" => "/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
                    "release_date" => "2020-11-25",
                    "title" => "The Croods: A New Age",
                    "video" => false,
                    "vote_average" => 7.9,
                    "vote_count" => 730,
                ],
                2 => [
                    "adult" => false,
                    "backdrop_path" => "/jIJfDVGKM8GXgpJc2XH2x7e11wm.jpg",
                    "genre_ids" => [
                        0 => 28,
                        1 => 53,
                        2 => 80,
                        3 => 18,
                    ],
                    "id" => 553604,
                    "original_language" => "en",
                    "original_title" => "Honest Thief",
                    "overview" => "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
                    "popularity" => 2220.746,
                    "poster_path" => "/zeD4PabP6099gpE0STWJrJrCBCs.jpg",
                    "release_date" => "2020-09-03",
                    "title" => "Honest Thief",
                    "video" => false,
                    "vote_average" => 7,
                    "vote_count" => 311,
                ],
            ],
            "total_pages" => 61,
            "total_results" => 1206,
        ];
    }

    private function fakeGenres()
    {
        return [
            "genres" => [
                0 => [
                    "id" => 28,
                    "name" => "Action",
                ],
                1 => [
                    "id" => 12,
                    "name" => "Adventure",
                ],
                2 => [
                    "id" => 16,
                    "name" => "Animation",
                ],
                3 => [
                    "id" => 35,
                    "name" => "Comedy",
                ],
                4 => [
                    "id" => 80,
                    "name" => "Crime",
                ],
                5 => [
                    "id" => 99,
                    "name" => "Documentary",
                ],
                6 => [
                    "id" => 18,
                    "name" => "Drama",
                ],
                7 => [
                    "id" => 10751,
                    "name" => "Family",
                ],
                8 => [
                    "id" => 14,
                    "name" => "Fantasy",
                ],
                9 => [
                    "id" => 36,
                    "name" => "History",
                ],
                10 => [
                    "id" => 27,
                    "name" => "Horror",
                ],
                11 => [
                    "id" => 10402,
                    "name" => "Music",
                ],
                12 => [
                    "id" => 9648,
                    "name" => "Mystery",
                ],
                13 => [
                    "id" => 10749,
                    "name" => "Romance",
                ],
                14 => [
                    "id" => 878,
                    "name" => "Science Fiction",
                ],
                15 => [
                    "id" => 10770,
                    "name" => "TV Movie",
                ],
                16 => [
                    "id" => 53,
                    "name" => "Thriller",
                ],
                17 => [
                    "id" => 10752,
                    "name" => "War",
                ],
                18 => [
                    "id" => 37,
                    "name" => "Western",
                ],
            ],
        ];
    }

    private function fakeSingleMovie()
    {
        return [
            "adult" => false,
            "backdrop_path" => "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
            "belongs_to_collection" => [
                "id" => 464577,
                "name" => "The Croods Collection",
                "poster_path" => "/ngKY2KzudNpC7j8a0OWjJRY0tHv.jpg",
                "backdrop_path" => "/8MjzBahFKCuQbwytpPPds7qboQa.jpg",
            ],
            "budget" => 65000000,
            "genres" => [
                0 => [
                    "id" => 12,
                    "name" => "Adventure",
                ],
                1 => [
                    "id" => 14,
                    "name" => "Fantasy",
                ],
                2 => [
                    "id" => 10751,
                    "name" => "Family",
                ],
                3 => [
                    "id" => 16,
                    "name" => "Animation",
                ],
            ],
            "homepage" => "https://www.dreamworks.com/movies/the-croods-2",
            "id" => 529203,
            "imdb_id" => "tt2850386",
            "original_language" => "en",
            "original_title" => "The Croods: A New Age",
            "overview" => "After leaving their cave, the Croods encounter their biggest threat since leaving: another family called the Bettermans, who claim and show to be better and evolved. Grug grows suspicious of the Betterman parents, Phil and Hope,  as they secretly plan to break up his daughter Eep with her loving boyfriend Guy to ensure that their daughter Dawn has a loving and smart partner to protect her.  Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
            "popularity" => 2570.332,
            "poster_path" => "/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
            "production_companies" => [
                0 => [
                    "id" => 33,
                    "logo_path" => "/8lvHyhjr8oUKOOy2dKXoALWKdp0.png",
                    "name" => "Universal Pictures",
                    "origin_country" => "US",
                ],
                1 => [
                    "id" => 521,
                    "logo_path" => "/kP7t6RwGz2AvvTkvnI1uteEwHet.png",
                    "name" => "DreamWorks Animation",
                    "origin_country" => "US",
                ],
            ],
            "production_countries" => [
                0 => [
                    "iso_3166_1" => "US",
                    "name" => "United States of America",
                ],
            ],
            "release_date" => "2020-11-25",
            "revenue" => 35930000,
            "runtime" => 95,
            "spoken_languages" => [
                0 => [
                    "english_name" => "English",
                    "iso_639_1" => "en",
                    "name" => "English",
                ],
            ],
            "status" => "Released",
            "tagline" => "The future ain't what it used to be.",
            "title" => "The Croods: A New Age",
            "video" => false,
            "vote_average" => 7.9,
            "vote_count" => 746,
            "credits" => [
                "cast" => [
                    0 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 2963,
                        "known_for_department" => "Acting",
                        "name" => "Nicolas Cage",
                        "original_name" => "Nicolas Cage",
                        "popularity" => 20.312,
                        "profile_path" => "/ar33qcWbEgREn07ZpXv5Pbj8hbM.jpg",
                        "cast_id" => 7,
                        "character" => "Grug Crood (voice)",
                        "credit_id" => "5b3527589251413cb3022305",
                        "order" => 0,
                    ],
                    1 => [
                        "adult" => false,
                        "gender" => 1,
                        "id" => 54693,
                        "known_for_department" => "Acting",
                        "name" => "Emma Stone",
                        "original_name" => "Emma Stone",
                        "popularity" => 11.825,
                        "profile_path" => "/cZ8a3QvAnj2cgcgVL6g4XaqPzpL.jpg",
                        "cast_id" => 8,
                        "character" => "Eep Crood (voice)",
                        "credit_id" => "5b3527699251413c8201d49f",
                        "order" => 1,
                    ],
                    2 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 10859,
                        "known_for_department" => "Acting",
                        "name" => "Ryan Reynolds",
                        "original_name" => "Ryan Reynolds",
                        "popularity" => 18.883,
                        "profile_path" => "/algQ1VEno2W9SesoArWcZTeF617.jpg",
                        "cast_id" => 6,
                        "character" => "Guy (voice)",
                        "credit_id" => "5b3527479251413c93022e90",
                        "order" => 2,
                    ],
                    3 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 22970,
                        "known_for_department" => "Acting",
                        "name" => "Peter Dinklage",
                        "original_name" => "Peter Dinklage",
                        "popularity" => 10.032,
                        "profile_path" => "/lRsRgnksAhBRXwAB68MFjmTtLrk.jpg",
                        "cast_id" => 14,
                        "character" => "Phil Betterman (voice)",
                        "credit_id" => "5bb97361c3a368241b01face",
                        "order" => 3,
                    ],
                    4 => [
                        "adult" => false,
                        "gender" => 1,
                        "id" => 41087,
                        "known_for_department" => "Acting",
                        "name" => "Leslie Mann",
                        "original_name" => "Leslie Mann",
                        "popularity" => 8.762,
                        "profile_path" => "/x3OS9RL3qsv50kzRtpR2OhbuTkr.jpg",
                        "cast_id" => 11,
                        "character" => "Hope Betterman (voice)",
                        "credit_id" => "5b35278c0e0a263ff0025984",
                        "order" => 4,
                    ],
                    5 => [
                        "adult" => false,
                        "gender" => 1,
                        "id" => 1663195,
                        "known_for_department" => "Acting",
                        "name" => "Kelly Marie Tran",
                        "original_name" => "Kelly Marie Tran",
                        "popularity" => 4.375,
                        "profile_path" => "/v2daUrk7hZryH6vtCWK9ESf6gAG.jpg",
                        "cast_id" => 16,
                        "character" => "Dawn Betterman (voice)",
                        "credit_id" => "5db930e20f2fbd001775dfa8",
                        "order" => 5,
                    ],
                    6 => [
                        "adult" => false,
                        "gender" => 1,
                        "id" => 2229,
                        "known_for_department" => "Acting",
                        "name" => "Catherine Keener",
                        "original_name" => "Catherine Keener",
                        "popularity" => 4.398,
                        "profile_path" => "/n4CTwGszs6cwS1wJRlDQ5Mlh7Ex.jpg",
                        "cast_id" => 9,
                        "character" => "Ugga Crood (voice)",
                        "credit_id" => "5b3527779251413c58025ff5",
                        "order" => 6,
                    ],
                    7 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 54729,
                        "known_for_department" => "Acting",
                        "name" => "Clark Duke",
                        "original_name" => "Clark Duke",
                        "popularity" => 3.193,
                        "profile_path" => "/bwCVCNsXCf3V22JEMAppunjGiLn.jpg",
                        "cast_id" => 13,
                        "character" => "Thunk Crood (voice)",
                        "credit_id" => "5b3527d8c3a3685326029009",
                        "order" => 7,
                    ],
                    8 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 42267,
                        "known_for_department" => "Sound",
                        "name" => "Randy Thom",
                        "original_name" => "Randy Thom",
                        "popularity" => 1.414,
                        "profile_path" => "/oWv5U4r7NcIlQjs0IxMWE3dsx2l.jpg",
                        "cast_id" => 17,
                        "character" => "Sandy Crood (voice)",
                        "credit_id" => "5f782f8e532acb00387a58a2",
                        "order" => 8,
                    ],
                    9 => [
                        "adult" => false,
                        "gender" => 1,
                        "id" => 9599,
                        "known_for_department" => "Acting",
                        "name" => "Cloris Leachman",
                        "original_name" => "Cloris Leachman",
                        "popularity" => 4.285,
                        "profile_path" => "/btosClScoBCcTjgv1ilIr9TaYvW.jpg",
                        "cast_id" => 12,
                        "character" => "Gran Crood (voice)",
                        "credit_id" => "5b35279b0e0a264011023bb4",
                        "order" => 9,
                    ],
                    10 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 66193,
                        "known_for_department" => "Acting",
                        "name" => "Chris Sanders",
                        "original_name" => "Chris Sanders",
                        "popularity" => 4.322,
                        "profile_path" => "/mrUm1agSL9Kj6dhV6ABVJvrwlie.jpg",
                        "cast_id" => 18,
                        "character" => "Belt (voice)",
                        "credit_id" => "5f782fa61f748b00352613c0",
                        "order" => 10,
                    ],
                    11 => [
                        "adult" => false,
                        "gender" => 1,
                        "id" => 15762,
                        "known_for_department" => "Acting",
                        "name" => "Tara Strong",
                        "original_name" => "Tara Strong",
                        "popularity" => 6.21,
                        "profile_path" => "/y9S3QzI3L5aARP8GYYO86rREKxU.jpg",
                        "cast_id" => 19,
                        "character" => "Sash (voice)",
                        "credit_id" => "5f782fbd7b7b4d003970ebbf",
                        "order" => 11,
                    ],
                ],
                "crew" => [
                    0 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 5666,
                        "known_for_department" => "Sound",
                        "name" => "Mark Mothersbaugh",
                        "original_name" => "Mark Mothersbaugh",
                        "popularity" => 1.512,
                        "profile_path" => null,
                        "credit_id" => "5fc3ce65420228003fc28497",
                        "department" => "Sound",
                        "job" => "Original Music Composer",
                    ],
                    1 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 8930,
                        "known_for_department" => "Acting",
                        "name" => "John Cleese",
                        "original_name" => "John Cleese",
                        "popularity" => 3.539,
                        "profile_path" => "/kg63gNYQtGPi2fSNIvCnVAclCbi.jpg",
                        "credit_id" => "5fe9cc10be4b36003c5edd3f",
                        "department" => "Writing",
                        "job" => "Characters",
                    ],
                    2 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 66193,
                        "known_for_department" => "Acting",
                        "name" => "Chris Sanders",
                        "original_name" => "Chris Sanders",
                        "popularity" => 4.322,
                        "profile_path" => "/mrUm1agSL9Kj6dhV6ABVJvrwlie.jpg",
                        "credit_id" => "5fa60b51a579f9003c76008f",
                        "department" => "Writing",
                        "job" => "Characters",
                    ],
                    3 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 66193,
                        "known_for_department" => "Acting",
                        "name" => "Chris Sanders",
                        "original_name" => "Chris Sanders",
                        "popularity" => 4.322,
                        "profile_path" => "/mrUm1agSL9Kj6dhV6ABVJvrwlie.jpg",
                        "credit_id" => "5fc3ce2e2bcf67003cc105f7",
                        "department" => "Writing",
                        "job" => "Story",
                    ],
                    4 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 71267,
                        "known_for_department" => "Writing",
                        "name" => "Kirk DeMicco",
                        "original_name" => "Kirk DeMicco",
                        "popularity" => 1.16,
                        "profile_path" => null,
                        "credit_id" => "5fa60b5bc68b690040a08cd4",
                        "department" => "Writing",
                        "job" => "Characters",
                    ],
                    5 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 71267,
                        "known_for_department" => "Writing",
                        "name" => "Kirk DeMicco",
                        "original_name" => "Kirk DeMicco",
                        "popularity" => 1.16,
                        "profile_path" => null,
                        "credit_id" => "5fc3ce24a885870042081b89",
                        "department" => "Writing",
                        "job" => "Story",
                    ],
                    6 => [
                        "adult" => false,
                        "gender" => 0,
                        "id" => 934181,
                        "known_for_department" => "Writing",
                        "name" => "Paul Fisher",
                        "original_name" => "Paul Fisher",
                        "popularity" => 1.218,
                        "profile_path" => null,
                        "credit_id" => "5fa60b9b323eba0041245c87",
                        "department" => "Writing",
                        "job" => "Screenplay",
                    ],
                    7 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 1003944,
                        "known_for_department" => "Writing",
                        "name" => "Dan Hageman",
                        "original_name" => "Dan Hageman",
                        "popularity" => 1.55,
                        "profile_path" => "/AjFtYtYu4OXftjmCfXDqvJKrpBT.jpg",
                        "credit_id" => "5b3526d2c3a368532f0264d6",
                        "department" => "Writing",
                        "job" => "Screenplay",
                    ],
                    8 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 1003945,
                        "known_for_department" => "Writing",
                        "name" => "Kevin Hageman",
                        "original_name" => "Kevin Hageman",
                        "popularity" => 2.592,
                        "profile_path" => "/28qbBKdzWwcwFjLNWGMrEjcKTsK.jpg",
                        "credit_id" => "5b3526f9c3a3685311021729",
                        "department" => "Writing",
                        "job" => "Screenplay",
                    ],
                    9 => [
                        "adult" => false,
                        "gender" => 0,
                        "id" => 1450348,
                        "known_for_department" => "Writing",
                        "name" => "Joel Crawford",
                        "original_name" => "Joel Crawford",
                        "popularity" => 2.709,
                        "profile_path" => null,
                        "credit_id" => "5b3526689251413ca00206f1",
                        "department" => "Directing",
                        "job" => "Director",
                    ],
                    10 => [
                        "adult" => false,
                        "gender" => 0,
                        "id" => 1767030,
                        "known_for_department" => "Writing",
                        "name" => "Bob Logan",
                        "original_name" => "Bob Logan",
                        "popularity" => 2.304,
                        "profile_path" => null,
                        "credit_id" => "5fa60baa1d820f0040c1f3bd",
                        "department" => "Writing",
                        "job" => "Screenplay",
                    ],
                    11 => [
                        "adult" => false,
                        "gender" => 2,
                        "id" => 2008016,
                        "known_for_department" => "Production",
                        "name" => "Mark Swift",
                        "original_name" => "Mark Swift",
                        "popularity" => 1.102,
                        "profile_path" => null,
                        "credit_id" => "5c432ed70e0a2667531a98c1",
                        "department" => "Production",
                        "job" => "Producer",
                    ],
                    12 => [
                        "adult" => false,
                        "gender" => 1,
                        "id" => 2867496,
                        "known_for_department" => "Crew",
                        "name" => "Lisa Curtis Saunders",
                        "original_name" => "Lisa Curtis Saunders",
                        "popularity" => 0.98,
                        "profile_path" => null,
                        "credit_id" => "5fbc1636d55697003f1b5c9d",
                        "department" => "Visual Effects",
                        "job" => "Pipeline Technical Director",
                    ],
                ],
            ],
            "videos" => [
                "results" => [
                    0 => [
                        "id" => "5f6aee86a6e2d2003a64b43c",
                        "iso_639_1" => "en",
                        "iso_3166_1" => "US",
                        "key" => "GkXeVIfbJOw",
                        "name" => "THE CROODS: A NEW AGE | Official Trailer",
                        "site" => "YouTube",
                        "size" => 1080,
                        "type" => "Trailer",
                    ],
                ],
            ],
            "images" => [
                "backdrops" => [
                    0 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
                        "height" => 1080,
                        "iso_639_1" => null,
                        "vote_average" => 5.454,
                        "vote_count" => 3,
                        "width" => 1920,
                    ],
                    1 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/rCxdJkk5PMCWIzRWcpqIxUaWnf1.jpg",
                        "height" => 1620,
                        "iso_639_1" => null,
                        "vote_average" => 5.312,
                        "vote_count" => 1,
                        "width" => 2880,
                    ],
                    2 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/ge5FfHLfGd5fLVLmsNVGEbXmFgL.jpg",
                        "height" => 2160,
                        "iso_639_1" => "en",
                        "vote_average" => 5.246,
                        "vote_count" => 2,
                        "width" => 3840,
                    ],
                    3 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/3zMItbdpW55w7RNyjBSHSxvOAoE.jpg",
                        "height" => 2160,
                        "iso_639_1" => "zh",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 3840,
                    ],
                    4 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/cDpeTwRRKLa1EG4UVHsWFRMmWv4.jpg",
                        "height" => 1080,
                        "iso_639_1" => null,
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1920,
                    ],
                    5 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/tEAKFKA0fMdvxV89pG35Ue3Pgba.jpg",
                        "height" => 1080,
                        "iso_639_1" => "es",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1920,
                    ],
                    6 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/xdrOEOvtgqy1nuRkL3F8CLYkTAX.jpg",
                        "height" => 1080,
                        "iso_639_1" => "es",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1920,
                    ],
                    7 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/owJYxFx1us5QVfEWCVPjwNv46hZ.jpg",
                        "height" => 1080,
                        "iso_639_1" => "es",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1920,
                    ],
                    8 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/8e0qphRaZ04wZ8Ebo6t8xSroBhy.jpg",
                        "height" => 1080,
                        "iso_639_1" => "es",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1920,
                    ],
                    9 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/mqmHhAf7OhJq5Tq81p7wFI0Fnde.jpg",
                        "height" => 1080,
                        "iso_639_1" => null,
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 1920,
                    ],
                    10 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/7skFtPwhhnJzaxQOVaF8l28gxPo.jpg",
                        "height" => 720,
                        "iso_639_1" => null,
                        "vote_average" => 4.982,
                        "vote_count" => 4,
                        "width" => 1280,
                    ],
                    11 => [
                        "aspect_ratio" => 1.7777777777778,
                        "file_path" => "/udfb8f5Z3uGOYM84qXdwGNiXnKp.jpg",
                        "height" => 2160,
                        "iso_639_1" => null,
                        "vote_average" => 0.0,
                        "vote_count" => 0,
                        "width" => 3840,
                    ],
                    12 => [
                        "aspect_ratio" => 1.7773851590106,
                        "file_path" => "/reDeoOvnih7Zv2xKXZAZL7w8KP6.jpg",
                        "height" => 1698,
                        "iso_639_1" => null,
                        "vote_average" => 0.0,
                        "vote_count" => 0,
                        "width" => 3018,
                    ],
                ],
                "posters" => [
                    0 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
                        "height" => 1500,
                        "iso_639_1" => "en",
                        "vote_average" => 5.648,
                        "vote_count" => 8,
                        "width" => 1000,
                    ],
                    1 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg",
                        "height" => 3000,
                        "iso_639_1" => "en",
                        "vote_average" => 5.588,
                        "vote_count" => 5,
                        "width" => 2000,
                    ],
                    2 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/nMLI9xkJTbgpZjMSrFiTUDv9WIG.jpg",
                        "height" => 1500,
                        "iso_639_1" => "fr",
                        "vote_average" => 5.522,
                        "vote_count" => 4,
                        "width" => 1000,
                    ],
                    3 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/s0GEywW0QG7R67WsKKrSsrRQpab.jpg",
                        "height" => 1500,
                        "iso_639_1" => "sk",
                        "vote_average" => 5.384,
                        "vote_count" => 2,
                        "width" => 1000,
                    ],
                    4 => [
                        "aspect_ratio" => 0.66791979949875,
                        "file_path" => "/f2YpOR3HiWaTtaqRLnGMNSjvgCE.jpg",
                        "height" => 1596,
                        "iso_639_1" => "pt",
                        "vote_average" => 5.384,
                        "vote_count" => 2,
                        "width" => 1066,
                    ],
                    5 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/79S2a9qzmfExdgcCKspNCHk2Rc4.jpg",
                        "height" => 1500,
                        "iso_639_1" => "en",
                        "vote_average" => 5.318,
                        "vote_count" => 3,
                        "width" => 1000,
                    ],
                    6 => [
                        "aspect_ratio" => 0.66652596032081,
                        "file_path" => "/bvkqVK7uPisrr8uSLHczTRNsdlv.jpg",
                        "height" => 2369,
                        "iso_639_1" => "en",
                        "vote_average" => 5.318,
                        "vote_count" => 3,
                        "width" => 1579,
                    ],
                    7 => [
                        "aspect_ratio" => 0.675,
                        "file_path" => "/a2fmufY8h0SirNKt37yprZdf7xi.jpg",
                        "height" => 1200,
                        "iso_639_1" => "es",
                        "vote_average" => 5.318,
                        "vote_count" => 3,
                        "width" => 810,
                    ],
                    8 => [
                        "aspect_ratio" => 0.66644090755164,
                        "file_path" => "/gcqq5pQg0xA4CwDO3WNw1XqlIKB.jpg",
                        "height" => 2953,
                        "iso_639_1" => "zh",
                        "vote_average" => 5.318,
                        "vote_count" => 3,
                        "width" => 1968,
                    ],
                    9 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/vvBRuYjyyfupUNxmOEISYbCK28i.jpg",
                        "height" => 1080,
                        "iso_639_1" => "sv",
                        "vote_average" => 5.312,
                        "vote_count" => 1,
                        "width" => 720,
                    ],
                    10 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/7TGnpQ4zO89zTrvvDly6fO2nGNy.jpg",
                        "height" => 1500,
                        "iso_639_1" => "en",
                        "vote_average" => 5.252,
                        "vote_count" => 4,
                        "width" => 1000,
                    ],
                    11 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/xwuurfM7GHRnoHmJeNGTNcTYhve.jpg",
                        "height" => 1425,
                        "iso_639_1" => "sk",
                        "vote_average" => 5.246,
                        "vote_count" => 2,
                        "width" => 950,
                    ],
                    12 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/scyMuCm6ec65gzMTEYVoPAQOlvV.jpg",
                        "height" => 3000,
                        "iso_639_1" => "en",
                        "vote_average" => 5.246,
                        "vote_count" => 2,
                        "width" => 2000,
                    ],
                    13 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/iQ5eAgJPieynVYbpEHSpXqf7UOY.jpg",
                        "height" => 1500,
                        "iso_639_1" => "es",
                        "vote_average" => 5.246,
                        "vote_count" => 2,
                        "width" => 1000,
                    ],
                    14 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/hMne7d6YLmAsdWw2rhiqdiN0INV.jpg",
                        "height" => 1080,
                        "iso_639_1" => "sv",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 720,
                    ],
                    15 => [
                        "aspect_ratio" => 0.675,
                        "file_path" => "/vRTScutueW9gLF3dSo2Za7o0v7n.jpg",
                        "height" => 2000,
                        "iso_639_1" => "pt",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1350,
                    ],
                    16 => [
                        "aspect_ratio" => 0.675,
                        "file_path" => "/1IEqv2CDDtT1TPN2KsewB5EUIyB.jpg",
                        "height" => 1600,
                        "iso_639_1" => "es",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1080,
                    ],
                    17 => [
                        "aspect_ratio" => 0.70740740740741,
                        "file_path" => "/inLmBfTD58OqBjoZ0ChMG1GlzMA.jpg",
                        "height" => 1080,
                        "iso_639_1" => "de",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 764,
                    ],
                    18 => [
                        "aspect_ratio" => 0.66572836030964,
                        "file_path" => "/neIkozO8tO8WxLWiXnHAzcMvbqi.jpg",
                        "height" => 1421,
                        "iso_639_1" => "zh",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 946,
                    ],
                    19 => [
                        "aspect_ratio" => 0.68,
                        "file_path" => "/mc5xmpDFWHfYQhrwsNVfEWi3Ruq.jpg",
                        "height" => 1000,
                        "iso_639_1" => "fr",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 680,
                    ],
                    20 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/jMHx39lZVjiDEZlOM6bN3WODTvk.jpg",
                        "height" => 1500,
                        "iso_639_1" => "es",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 1000,
                    ],
                    21 => [
                        "aspect_ratio" => 0.6669014084507,
                        "file_path" => "/hLJzB16xpaFNuqI4hK04GezrSQE.jpg",
                        "height" => 1420,
                        "iso_639_1" => "ru",
                        "vote_average" => 5.172,
                        "vote_count" => 1,
                        "width" => 947,
                    ],
                    22 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/5DuSFFEn41ZDc6mSqMm0twrWGn.jpg",
                        "height" => 3000,
                        "iso_639_1" => "en",
                        "vote_average" => 5.138,
                        "vote_count" => 8,
                        "width" => 2000,
                    ],
                    23 => [
                        "aspect_ratio" => 0.71466666666667,
                        "file_path" => "/duBm89e3IfRtFvfbNhaAnHEpzhb.jpg",
                        "height" => 1500,
                        "iso_639_1" => "zh",
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 1072,
                    ],
                    24 => [
                        "aspect_ratio" => 0.70266666666667,
                        "file_path" => "/hNOiqUp92FQkyZfGLQE4ouCWVoS.jpg",
                        "height" => 1500,
                        "iso_639_1" => "zh",
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 1054,
                    ],
                    25 => [
                        "aspect_ratio" => 0.66680743243243,
                        "file_path" => "/zyZnkWIfa6hWcy2enCF5aIrCDA.jpg",
                        "height" => 2368,
                        "iso_639_1" => "en",
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 1579,
                    ],
                    26 => [
                        "aspect_ratio" => 0.67444444444444,
                        "file_path" => "/wArOltPlZ6luTozciNpkOMXwZlT.jpg",
                        "height" => 900,
                        "iso_639_1" => "pt",
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 607,
                    ],
                    27 => [
                        "aspect_ratio" => 0.66791979949875,
                        "file_path" => "/ldjx1dVWI4nKKtvvXjxP0HjAsjz.jpg",
                        "height" => 1596,
                        "iso_639_1" => "pt",
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 1066,
                    ],
                    28 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/xRonXF2krIE9cW0Wx2YuqrK16mV.jpg",
                        "height" => 1608,
                        "iso_639_1" => "en",
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 1072,
                    ],
                    29 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/bdxrpkfbStelmrixa96mbpIrbln.jpg",
                        "height" => 1620,
                        "iso_639_1" => "it",
                        "vote_average" => 5.106,
                        "vote_count" => 2,
                        "width" => 1080,
                    ],
                    30 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/xE3IrPU7D6God6cWvNFu7vzHAWX.jpg",
                        "height" => 1350,
                        "iso_639_1" => "en",
                        "vote_average" => 5.056,
                        "vote_count" => 5,
                        "width" => 900,
                    ],
                    31 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/laT4DR1XUCSLAvkaFFa7dT5KAZs.jpg",
                        "height" => 1200,
                        "iso_639_1" => "mo",
                        "vote_average" => 0.0,
                        "vote_count" => 0,
                        "width" => 800,
                    ],
                    32 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/pfSvoKuRV6Xqax1MktfdNe7qfqY.jpg",
                        "height" => 960,
                        "iso_639_1" => "vi",
                        "vote_average" => 0.0,
                        "vote_count" => 0,
                        "width" => 640,
                    ],
                    33 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/A9soWTfZEDKIMXmPZSRg5LFgQ5W.jpg",
                        "height" => 1500,
                        "iso_639_1" => null,
                        "vote_average" => 0.0,
                        "vote_count" => 0,
                        "width" => 1000,
                    ],
                    34 => [
                        "aspect_ratio" => 0.66666666666667,
                        "file_path" => "/jVEEZZCh4qecLWjuYXjqbj3o8Gy.jpg",
                        "height" => 1500,
                        "iso_639_1" => null,
                        "vote_average" => 0.0,
                        "vote_count" => 0,
                        "width" => 1000,
                    ],
                ],
            ],
        ];
    }

    private function fakeSearchMovies()
    {
        return [
            "page" => 1,
            "results" => [
                0 => [
                    "adult" => false,
                    "backdrop_path" => "/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg",
                    "genre_ids" => [
                        0 => 12,
                        1 => 35,
                        2 => 14,
                    ],
                    "id" => 512200,
                    "original_language" => "en",
                    "original_title" => "Jumanji: The Next Level",
                    "overview" => "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
                    "popularity" => 95.661,
                    "poster_path" => "/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg",
                    "release_date" => "2019-12-04",
                    "title" => "Jumanji: The Next Level",
                    "video" => false,
                    "vote_average" => 7,
                    "vote_count" => 5171,
                ],
            ]
        ];
    }
}
